spring:
  messages:
    basename: Validationmessages
  application:
    name: mortgage-app

mortgage:
  interest-rates:
    - maturityPeriod: 10
      interestRate: 3.5
      lastUpdate: 2026-03-12T00:00:00
    - maturityPeriod: 20
      interestRate: 4.1
      lastUpdate: 2026-03-12T00:00:00
    - maturityPeriod: 30
      interestRate: 2.8
      lastUpdate: 2026-03-12T00:00:00


